language: java
sudo: required
dist: xenial
jdk:
  - openjdk8
branches:
  only:
    - master
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
before_install:
  - chmod +x gradlew
install:
  - ./gradlew jar
script:
  - ./gradlew distZip
  - cd $HOME/build/distributions/
  - unzip job-hunting-helper-1.0.0.RELEASE.zip
  - chmod +x job-hunting-helper-1.0.0.RELEASE/bin/job-hunting-helper
  - ./job-hunting-helper-1.0.0.RELEASE/bin/job-hunting-helper ${industry} ${cities} ${companies}